#!/usr/bin/env bash

set -euo pipefail

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/togethercomputer/together-go,github.com/togethercomputer/together-go-staging"

go build -o terraform-provider-together
