#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/togethercomputer/together-go,github.com/togethercomputer/together-go-staging"

echo "==> Running tests"
go test ./... "$@"
